# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proximity.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proximity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fproximity.proto\x12\tproximity\"J\n\x10ProximityRequest\x12\x0c\n\x04lat1\x18\x01 \x01(\x01\x12\x0c\n\x04lon1\x18\x02 \x01(\x01\x12\x0c\n\x04lat2\x18\x03 \x01(\x01\x12\x0c\n\x04lon2\x18\x04 \x01(\x01\"!\n\x11ProximityResponse\x12\x0c\n\x04near\x18\x01 \x01(\x08\x32_\n\x10ProximityService\x12K\n\x0e\x43heckProximity\x12\x1b.proximity.ProximityRequest\x1a\x1c.proximity.ProximityResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proximity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROXIMITYREQUEST']._serialized_start=30
  _globals['_PROXIMITYREQUEST']._serialized_end=104
  _globals['_PROXIMITYRESPONSE']._serialized_start=106
  _globals['_PROXIMITYRESPONSE']._serialized_end=139
  _globals['_PROXIMITYSERVICE']._serialized_start=141
  _globals['_PROXIMITYSERVICE']._serialized_end=236
# @@protoc_insertion_point(module_scope)
